---
name: "Close stale issues and PRs"

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "25 2 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@5bef64f19d7facfb25b37b414482c7164d639639 # v9.1.0
        with:
          # yamllint disable rule:line-length
          stale-issue-message: "This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 10 days."
          stale-pr-message: "This PR is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 10 days."
          close-issue-message: "This issue was closed because it has been stalled for 10 days with no activity."
          close-pr-message: "This PR was closed because it has been stalled for 10 days with no activity."
          # yamllint enable rule:line-length
          days-before-stale: 30
          days-before-close: 10
          stale-issue-label: "stale"
          stale-pr-label: "stale"
